name: sefarad
version: 1.0.0
dependencies:
  polymer: any
  angular: 1.1.0
  browser: any
  http_server: '>=0.9.3 <0.10.0'
  web_components: '>=0.8.0 <0.11.0'
  mongo_dart: any
dev_dependencies:
  unittest: '>=0.11.0+5 <0.13.0'
transformers:
- angular
