name: sefarad
version: 1.0.0
dependencies:
  angular: 1.0.0
  browser: any
  http_server: '>=0.9.3 <0.10.0'
  web_components: '>=0.8.0 <0.9.0'
dev_dependencies:
  mock: '>=0.11.0+2 <0.12.0'
  unittest: '>=0.11.0+5 <0.12.0'
transformers:
- angular:
    html_files:
      - lib/component/recipe_book.html
